name = "cloudfare-salary-tracker"
compatibility_date = "2026-05-23"
pages_build_output_dir = "./dist"

[[d1_databases]]
binding = "DB"
database_name = "salary-cycle-tracker-db"
database_id = "b926b62a-5cf2-4061-a577-415c1c859b3a"
